version: 1
update_configs:
  - package_manager: ":maven"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true